server:
  port: 8003
spring:
  application:
    name: service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
    # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
    # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#nacos服务器
#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4FeTQwLmQ11qxm4yzgXb
      keysecret: ENC(9jCRvjkG1TFUTDtCogC47QSMMsve6q4uw7vjaqIUtSF2CytYn2SecA==)