#服务器端口号
server:
  port: 8001
#服务名
spring:
  application:
    name: guli-oss
#环境设置：dev、test、prod
  profiles:
    active: dev
#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4FeTQwLmQ11qxm4yzgXb
      keysecret: ENC(9jCRvjkG1TFUTDtCogC47QSMMsve6q4uw7vjaqIUtSF2CytYn2SecA==)
      bucketname: guli-file-whl
      filehost: avatar